"""
DanioBrain — Vectorized Neural Runtime Engine for Danionella cerebrum (650,000 Neurons)
Provides an external-facing Python SDK for robotics, game engines, and AI simulations.
Schema Version 2.0: Grounded in the Charité Berlin / Judkewitz Lab Atlas (bioRxiv 2026).
"""

from __future__ import annotations
import os
import json
from pathlib import Path
import numpy as np
from dataclasses import dataclass
from typing import Dict, Any, Optional, List, Union

@dataclass
class DanioAction:
    """Motor commands generated by Danionella cerebrum vertebrate brain."""
    tail_thrust: float             # Axial propulsion (0.0 to 1.0)
    heading_yaw: float             # Left/right rudder steering (-1.0 to 1.0)
    fin_pitch: float               # Pectoral fin pitch (-1.0 to 1.0)
    drumming_sound_active: bool    # True when 140 dB sonic pulse fires
    drumming_frequency_hz: float   # Frequency of acoustic pulse (60 - 120 Hz)
    drumming_spl_db: float         # Sound Pressure Level in decibels (up to 140.2 dB)
    mauthner_escape: bool          # High-speed C-start escape reflex
    population_firing_rate: float  # Mean population firing rate across 650k neurons (Hz)
    regional_activity: Dict[str, float] # Macro division calcium levels

    def to_dict(self) -> Dict[str, Any]:
        return {
            "tail_thrust": round(float(self.tail_thrust), 4),
            "heading_yaw": round(float(self.heading_yaw), 4),
            "fin_pitch": round(float(self.fin_pitch), 4),
            "drumming_sound_active": bool(self.drumming_sound_active),
            "drumming_frequency_hz": round(float(self.drumming_frequency_hz), 1),
            "drumming_spl_db": round(float(self.drumming_spl_db), 1),
            "mauthner_escape": bool(self.mauthner_escape),
            "population_firing_rate": round(float(self.population_firing_rate), 2),
            "regional_activity": {k: round(float(v), 3) for k, v in self.regional_activity.items()}
        }

class DanioBrain:
    """
    High-Performance Vertebrate Brain Simulation Engine.
    Simulates Adult Danionella cerebrum: 650,000 modeled neurons, 203 empirical regions.
    """

    def __init__(self, data: np.lib.npyio.NpzFile):
        # Determine schema version
        raw_version = str(data["schema_version"]) if "schema_version" in data else "1.0"
        self.schema_version = "2.0" if "2.0" in raw_version else "1.0"

        self.region_names: np.ndarray = data["region_names"]
        self.num_regions = len(self.region_names)
        self.empirical_region_count = self.num_regions

        if self.schema_version == "2.0":
            self.region_ids: np.ndarray = data["region_ids"]
            self.region_abbreviations: np.ndarray = data["region_abbreviations"]
            self.region_divisions: np.ndarray = data["region_divisions"]
            self.region_centroids: np.ndarray = data["region_centroids"]
            self.region_centroids_voxel: np.ndarray = data["region_centroids_voxel"]
            self.region_volumes: np.ndarray = data["region_volumes"]

            # Model neuron population
            self.coords_xyz: np.ndarray = data["model_neuron_coords_xyz"]
            self.model_neuron_coords_xyz = self.coords_xyz
            self.neuron_region_ids: np.ndarray = data["model_neuron_region_ids"]
            self.neurotransmitters: np.ndarray = data["neurotransmitter_ids"]
            self.cell_type_ids: np.ndarray = data["cell_type_ids"]
            self.resting_potentials: np.ndarray = data["model_resting_potentials"]
            self.thresholds: np.ndarray = data["model_thresholds"]
            self.time_constants: np.ndarray = data["model_time_constants"]

            # Reconstruct macro tract matrix from sparse arrays
            self.tract_matrix = np.zeros((self.num_regions, self.num_regions), dtype=np.float32)
            src = data["region_tract_src"]
            dst = data["region_tract_dst"]
            w = data["region_tract_weight"]
            valid_tracts = (src < self.num_regions) & (dst < self.num_regions)
            self.tract_matrix[src[valid_tracts], dst[valid_tracts]] = w[valid_tracts]

            self.hub_neuron_ids: np.ndarray = data["hub_neuron_ids"]
            self.mauthner_hub = self.hub_neuron_ids[:16]
            self.sonic_hub = self.hub_neuron_ids[16:48] if len(self.hub_neuron_ids) >= 48 else self.hub_neuron_ids
            self.motor_hub = self.sonic_hub
            self.tectum_hub = self.hub_neuron_ids[:16]

            # Metadata & Provenance
            meta_val = data["metadata_json"]
            meta_str = str(meta_val[0]) if hasattr(meta_val, "ndim") and meta_val.ndim > 0 else str(meta_val)
            self.metadata = json.loads(meta_str)

            prov_val = data["provenance_json"]
            prov_str = str(prov_val[0]) if hasattr(prov_val, "ndim") and prov_val.ndim > 0 else str(prov_val)
            self.provenance = json.loads(prov_str)
        else:
            # Fallback for Schema 1.0
            self.region_ids: np.ndarray = data["region_ids"]
            self.coords_xyz: np.ndarray = data["coords_xyz"]
            self.model_neuron_coords_xyz = self.coords_xyz
            self.neuron_region_ids = self.region_ids
            self.neurotransmitters: np.ndarray = data["neurotransmitters"]
            self.resting_potentials: np.ndarray = data["resting_potentials"]
            self.thresholds: np.ndarray = data["thresholds"]
            self.time_constants: np.ndarray = data["time_constants"]
            self.tract_matrix: np.ndarray = data["tract_matrix"]

            self.tectum_hub: np.ndarray = data["tectum_hub"]
            self.sonic_hub: np.ndarray = data["sonic_hub"]
            self.mauthner_hub: np.ndarray = data["mauthner_hub"]
            self.motor_hub: np.ndarray = data["motor_hub"]

            meta_val = data["metadata_json"]
            meta_str = str(meta_val[0]) if hasattr(meta_val, "ndim") and meta_val.ndim > 0 else str(meta_val)
            self.metadata = json.loads(meta_str)
            self.provenance = {}

        self.num_neurons = len(self.coords_xyz)
        self.model_neuron_count = self.num_neurons
        self.status = "ATLAS / EMPIRICAL REGIONS · MODELED NEURON POPULATION"

        # Runtime dynamic states
        self.region_calcium = np.zeros(self.num_regions, dtype=np.float32)
        hub_len = len(self.motor_hub) if hasattr(self, "motor_hub") and len(self.motor_hub) > 0 else 16
        self.hub_potentials = np.zeros(hub_len, dtype=np.float32) - 65.0

        self.drum_timer = 0.0
        self.drum_refractory = 0.0
        self.escape_cooldown = 0.0
        self.step_count = 0

        # Division indices cache
        self.division_indices: Dict[str, List[int]] = {
            "Telencephalon": [],
            "Diencephalon": [],
            "Mesencephalon": [],
            "Cerebellum": [],
            "Rhombencephalon": [],
            "Motor & Sonic Drumming": [],
            "Motor & Spinal": [],
            "Tracts & Commissures": [],
            "Anatomical Appendages": []
        }

        for idx, name in enumerate(self.region_names):
            div = None
            if hasattr(self, "region_divisions") and len(self.region_divisions) > idx:
                div = str(self.region_divisions[idx])

            if not div or div in ("Unassigned", "whole brain"):
                name_str = str(name).lower()
                if name.startswith("Tel_") or "telencephal" in name_str or "pallium" in name_str or "olfactory" in name_str:
                    div = "Telencephalon"
                elif name.startswith("Di_") or "diencephal" in name_str or "thalam" in name_str or "habenula" in name_str:
                    div = "Diencephalon"
                elif name.startswith("Mes_") or "tectum" in name_str or "mesencephal" in name_str:
                    div = "Mesencephalon"
                elif name.startswith("Ce_") or "cerebell" in name_str:
                    div = "Cerebellum"
                elif name.startswith("Rh_") or "vagal" in name_str or "rhombencephal" in name_str or "reticulo" in name_str:
                    div = "Rhombencephalon"
                elif "spinal" in name_str or "motor" in name_str or "sonic" in name_str:
                    div = "Motor & Spinal"
                else:
                    div = "Mesencephalon"

            # Assign to primary division
            if div in self.division_indices:
                self.division_indices[div].append(idx)

            # Cross-alias "Motor & Spinal" and "Motor & Sonic Drumming"
            if div in ("Motor & Spinal", "Motor & Sonic Drumming"):
                if idx not in self.division_indices["Motor & Sonic Drumming"]:
                    self.division_indices["Motor & Sonic Drumming"].append(idx)
                if idx not in self.division_indices["Motor & Spinal"]:
                    self.division_indices["Motor & Spinal"].append(idx)

    @classmethod
    def load(cls, filepath: Optional[str] = None) -> DanioBrain:
        """Load brain memory package from disk (auto-detecting v2 or 650k)."""
        root_dir = Path(__file__).resolve().parent.parent.parent

        if filepath is None or filepath in ("danio_brain_v2.npz", "danio_brain_650k.npz"):
            candidates = [
                root_dir / "danio_brain_v2.npz",
                Path("danio_brain_v2.npz"),
                root_dir / "danio_brain_650k.npz",
                Path("danio_brain_650k.npz")
            ]
            target = None
            for cand in candidates:
                if cand.exists():
                    target = str(cand)
                    break
            if not target:
                raise FileNotFoundError("Neither 'danio_brain_v2.npz' nor 'danio_brain_650k.npz' found.")
            filepath = target
        elif not os.path.exists(filepath):
            cand = root_dir / filepath
            if cand.exists():
                filepath = str(cand)
            else:
                raise FileNotFoundError(f"Danionella brain package not found at '{filepath}'.")

        data = np.load(filepath, allow_pickle=True)
        return cls(data)

    def step(self, sensory: Optional[Dict[str, Any]] = None, dt: float = 0.02) -> DanioAction:
        """
        Execute one biological simulation step (dt in seconds).
        50 Hz integration closed-loop with sensorimotor reflexes.
        """
        self.step_count += 1
        sensory = sensory or {}

        vis_lum = float(sensory.get("visual_luminance", 0.5))
        prey_ang = float(sensory.get("visual_prey_angle", 0.0))
        threat = float(sensory.get("predator_threat", 0.0))
        flow = float(sensory.get("water_flow_velocity", 0.05))
        sound_hz = float(sensory.get("acoustic_stimulus_hz", 0.0))
        sound_db = float(sensory.get("acoustic_stimulus_db", 0.0))

        # 1. Drive sensory regions
        sensory_drive = np.zeros(self.num_regions, dtype=np.float32)

        # Optic Tectum activation
        tectum_idxs = self.division_indices.get("Mesencephalon", [])
        angle_rad = np.clip(prey_ang / 90.0, -1.0, 1.0)
        for idx in tectum_idxs:
            name = str(self.region_names[idx]).lower()
            base_vis = vis_lum * 0.4
            if "_l" in name or " left" in name or name.endswith(" l"):
                sensory_drive[idx] += base_vis + max(0.0, angle_rad) * 0.6
            elif "_r" in name or " right" in name or name.endswith(" r"):
                sensory_drive[idx] += base_vis + max(0.0, -angle_rad) * 0.6
            else:
                sensory_drive[idx] += base_vis

        # Lateral line & Cerebellum flow activation
        cereb_idxs = self.division_indices.get("Cerebellum", [])
        for idx in cereb_idxs:
            sensory_drive[idx] += min(1.0, abs(flow) * 2.5) * 0.5

        # Auditory / Lateral line drive to Hindbrain
        rhomb_idxs = self.division_indices.get("Rhombencephalon", [])
        if sound_db > 40.0:
            sound_intensity = min(1.0, (sound_db - 40.0) / 60.0)
            for idx in rhomb_idxs:
                name = str(self.region_names[idx]).lower()
                if "auditory" in name or "lateral" in name or "octav" in name:
                    sensory_drive[idx] += sound_intensity * 0.8

        # 2. Inter-regional Connectome Recurrent Dynamics
        decay_factor = float(np.exp(-dt / 0.12)) # 120ms calcium decay
        synaptic_input = np.dot(self.tract_matrix.T, self.region_calcium) * 0.25
        noise = np.random.normal(0, 0.02, self.num_regions).astype(np.float32)

        self.region_calcium = self.region_calcium * decay_factor + synaptic_input * dt + sensory_drive * 0.4 + noise
        self.region_calcium = np.clip(self.region_calcium, 0.0, 1.5)

        # 3. Mauthner Escape Reflex Circuit (ultra-fast C-start)
        mauthner_triggered = False
        if threat > 0.65 and self.escape_cooldown <= 0.0:
            mauthner_triggered = True
            self.escape_cooldown = 0.5 # 500ms refractory
            for idx in rhomb_idxs:
                name = str(self.region_names[idx]).lower()
                if "mauthner" in name or "mid2" in name:
                    self.region_calcium[idx] = 1.4
        else:
            self.escape_cooldown = max(0.0, self.escape_cooldown - dt)

        # 4. Sonic Drumming Apparatus (>140 dB pulse generation)
        motor_idxs = self.division_indices.get("Motor & Sonic Drumming", [])
        sonic_drive = 0.0
        for idx in motor_idxs:
            name = str(self.region_names[idx]).lower()
            if "sonic" in name or "drum" in name or "motor" in name:
                sonic_drive += float(self.region_calcium[idx])

        tel_idxs = self.division_indices.get("Telencephalon", [])
        tel_drive = np.mean([self.region_calcium[i] for i in tel_idxs]) if tel_idxs else 0.2
        drumming_active = False
        drum_freq = 0.0
        drum_spl = 0.0

        if self.drum_refractory <= 0.0:
            if sonic_drive > 0.85 or (sound_hz > 50.0 and tel_drive > 0.4):
                drumming_active = True
                drum_freq = float(np.random.uniform(60.0, 120.0))
                drum_spl = float(np.random.uniform(132.0, 140.2)) # Up to 140.2 dB SPL
                self.drum_refractory = float(np.random.uniform(0.3, 0.8))
        else:
            self.drum_refractory = max(0.0, self.drum_refractory - dt)

        # 5. Compute Motor Outputs
        spin_idxs = [i for i in motor_idxs if "sp" in str(self.region_names[i]).lower() or "motor" in str(self.region_names[i]).lower()]
        if not spin_idxs:
            spin_idxs = motor_idxs

        left_candidates = [self.region_calcium[i] for i in spin_idxs if "_l" in str(self.region_names[i]).lower() or "left" in str(self.region_names[i]).lower()]
        right_candidates = [self.region_calcium[i] for i in spin_idxs if "_r" in str(self.region_names[i]).lower() or "right" in str(self.region_names[i]).lower()]

        left_motor = float(np.mean(left_candidates)) if left_candidates else (float(np.mean(self.region_calcium[spin_idxs])) if len(spin_idxs) > 0 else 0.2)
        right_motor = float(np.mean(right_candidates)) if right_candidates else (float(np.mean(self.region_calcium[spin_idxs])) if len(spin_idxs) > 0 else 0.2)

        if mauthner_triggered:
            tail_thrust = 1.0
            heading_yaw = 1.0 if np.random.rand() > 0.5 else -1.0
            fin_pitch = 0.2
        else:
            base_drive = float(np.clip((left_motor + right_motor) * 0.7, 0.05, 0.95))
            rhythm = float(0.5 + 0.5 * np.sin(self.step_count * 0.4))
            tail_thrust = float(np.clip(base_drive * rhythm, 0.0, 1.0))
            steering_delta = float(right_motor - left_motor)
            heading_yaw = float(np.clip(steering_delta * 1.5, -1.0, 1.0))
            cereb_level = float(np.mean([self.region_calcium[i] for i in cereb_idxs])) if cereb_idxs else 0.2
            fin_pitch = float(np.clip((cereb_level - 0.2) * 0.5, -1.0, 1.0))

        # 6. Global Population Statistics
        mean_calcium = float(np.mean(self.region_calcium))
        pop_rate = float(12.5 + mean_calcium * 24.0)

        regional_summary = {}
        for div_name in ["Telencephalon", "Diencephalon", "Mesencephalon", "Cerebellum", "Rhombencephalon", "Motor & Sonic Drumming"]:
            idx_list = self.division_indices.get(div_name, [])
            regional_summary[div_name] = float(np.mean([self.region_calcium[i] for i in idx_list])) if idx_list else 0.0

        return DanioAction(
            tail_thrust=tail_thrust,
            heading_yaw=heading_yaw,
            fin_pitch=fin_pitch,
            drumming_sound_active=drumming_active,
            drumming_frequency_hz=drum_freq,
            drumming_spl_db=drum_spl,
            mauthner_escape=mauthner_triggered,
            population_firing_rate=pop_rate,
            regional_activity=regional_summary
        )

    def get_cranial_snapshot(self, sample_size: int = 2000) -> Dict[str, Any]:
        """
        Sample active 3D neuron coordinates and their calcium intensities for web visualization.
        """
        step = max(1, self.num_neurons // sample_size)
        sample_indices = np.arange(0, self.num_neurons, step)[:sample_size]

        sample_coords = self.coords_xyz[sample_indices]
        sample_regs = self.neuron_region_ids[sample_indices]
        sample_calcium = self.region_calcium[sample_regs]

        return {
            "coords": sample_coords.tolist(),
            "calcium": sample_calcium.tolist(),
            "regions": sample_regs.tolist()
        }

    def info(self) -> str:
        """Pretty summary of brain model."""
        meta = self.metadata
        prov = self.provenance
        doi = prov.get("doi") or meta.get("source_reference", {}).get("doi", "10.64898/2026.03.09.710483v1")
        template = meta.get("atlas_version") or "dc_mixed_hhg6@1.0"
        return (
            f"========================================================\n"
            f" DANIO: Adult Danionella cerebrum Vertebrate Brain (v{self.schema_version})\n"
            f"========================================================\n"
            f" Organism:        Danionella cerebrum (Adult Teleost Vertebrate)\n"
            f" Modeled Neurons: {self.num_neurons:,} computational neurons (volume-constrained)\n"
            f" Atlas Regions:   {self.num_regions} registered anatomical structures\n"
            f" Reference Space: {template} (2.5 um isotropic isovoxels)\n"
            f" DOI Reference:   https://doi.org/{doi}\n"
            f" Cranial Volume:  ~0.60 mm3 (Optical Transparency)\n"
            f" Acoustic Motor:  >140 dB SPL drumming apparatus\n"
            f" Scientific St.:  ATLAS / EMPIRICAL REGIONS · MODELED POPULATION\n"
            f" License:         CC-BY-NC-SA 4.0\n"
            f"========================================================"
        )
