"""
DanioBrain — Vectorized Neural Runtime Engine for Danionella cerebrum (650,000 Neurons)
Provides an external-facing Python SDK for robotics, game engines, and AI simulations.
"""

from __future__ import annotations
import os
import json
import numpy as np
from dataclasses import dataclass
from typing import Dict, Any, Optional, List, Union

@dataclass
class DanioAction:
    """Motor commands generated by Danionella cerebrum vertebrate brain."""
    tail_thrust: float             # Axial propulsion (0.0 to 1.0)
    heading_yaw: float             # Left/right rudder steering (-1.0 to 1.0)
    fin_pitch: float               # Pectoral fin pitch (-1.0 to 1.0)
    drumming_sound_active: bool    # True when 140 dB sonic pulse fires
    drumming_frequency_hz: float   # Frequency of acoustic pulse (60 - 120 Hz)
    drumming_spl_db: float         # Sound Pressure Level in decibels (up to 140.2 dB)
    mauthner_escape: bool          # High-speed C-start escape reflex
    population_firing_rate: float  # Mean population firing rate across 650k neurons (Hz)
    regional_activity: Dict[str, float] # Macro division calcium levels

    def to_dict(self) -> Dict[str, Any]:
        return {
            "tail_thrust": round(float(self.tail_thrust), 4),
            "heading_yaw": round(float(self.heading_yaw), 4),
            "fin_pitch": round(float(self.fin_pitch), 4),
            "drumming_sound_active": bool(self.drumming_sound_active),
            "drumming_frequency_hz": round(float(self.drumming_frequency_hz), 1),
            "drumming_spl_db": round(float(self.drumming_spl_db), 1),
            "mauthner_escape": bool(self.mauthner_escape),
            "population_firing_rate": round(float(self.population_firing_rate), 2),
            "regional_activity": {k: round(float(v), 3) for k, v in self.regional_activity.items()}
        }

class DanioBrain:
    """
    High-Performance Vertebrate Brain Simulation Engine.
    Simulates Adult Danionella cerebrum: 650,000 neurons, 203 anatomical regions.
    """

    def __init__(self, data: np.lib.npyio.NpzFile):
        self.region_names: np.ndarray = data["region_names"]
        self.region_ids: np.ndarray = data["region_ids"]
        self.coords_xyz: np.ndarray = data["coords_xyz"]
        self.neurotransmitters: np.ndarray = data["neurotransmitters"]
        self.resting_potentials: np.ndarray = data["resting_potentials"]
        self.thresholds: np.ndarray = data["thresholds"]
        self.time_constants: np.ndarray = data["time_constants"]
        self.tract_matrix: np.ndarray = data["tract_matrix"] # (203, 203)
        
        self.tectum_hub: np.ndarray = data["tectum_hub"]
        self.sonic_hub: np.ndarray = data["sonic_hub"]
        self.mauthner_hub: np.ndarray = data["mauthner_hub"]
        self.motor_hub: np.ndarray = data["motor_hub"]
        
        self.metadata = json.loads(str(data["metadata_json"]))
        self.num_neurons = len(self.region_ids)
        self.num_regions = len(self.region_names)
        
        # Runtime dynamic states
        # Macro regional states (203,)
        self.region_calcium = np.zeros(self.num_regions, dtype=np.float32)
        # Membrane potentials of command hubs (sampled microcircuits)
        self.hub_potentials = np.zeros(len(self.motor_hub), dtype=np.float32) - 65.0
        
        # Drumming accumulator and cooldown
        self.drum_timer = 0.0
        self.drum_refractory = 0.0
        self.escape_cooldown = 0.0
        self.step_count = 0
        
        # Division indices cache
        self.division_indices: Dict[str, List[int]] = {
            "Telencephalon": [],
            "Diencephalon": [],
            "Mesencephalon": [],
            "Cerebellum": [],
            "Rhombencephalon": [],
            "Motor & Sonic Drumming": []
        }
        for idx, name in enumerate(self.region_names):
            if name.startswith("Tel_"):
                self.division_indices["Telencephalon"].append(idx)
            elif name.startswith("Di_"):
                self.division_indices["Diencephalon"].append(idx)
            elif name.startswith("Mes_"):
                self.division_indices["Mesencephalon"].append(idx)
            elif name.startswith("Ce_"):
                self.division_indices["Cerebellum"].append(idx)
            elif name.startswith("Rh_"):
                self.division_indices["Rhombencephalon"].append(idx)
            else:
                self.division_indices["Motor & Sonic Drumming"].append(idx)

    @classmethod
    def load(cls, filepath: str = "danio_brain_650k.npz") -> DanioBrain:
        """Load brain memory package from disk."""
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Danionella brain package not found at '{filepath}'. Run build_memory.py first.")
        data = np.load(filepath, allow_pickle=True)
        return cls(data)

    def step(self, sensory: Optional[Dict[str, Any]] = None, dt: float = 0.02) -> DanioAction:
        """
        Execute one biological simulation step (dt in seconds).
        
        Args:
            sensory: Sensory inputs dictionary:
                - visual_luminance: 0.0 to 1.0 (ambient brightness)
                - visual_prey_angle: -90.0 to 90.0 (degrees to target)
                - predator_threat: 0.0 to 1.0 (approaching predator size/velocity)
                - water_flow_velocity: m/s (lateral line rheotaxis input)
                - acoustic_stimulus_hz: frequency of nearby sounds (vibrational)
                - acoustic_stimulus_db: loudness of auditory stimulus
            dt: integration time delta (default 0.02s = 50 Hz loop)
        
        Returns:
            DanioAction containing motor thrust, fin yaw, acoustic drumming, and firing telemetry.
        """
        self.step_count += 1
        sensory = sensory or {}
        
        vis_lum = float(sensory.get("visual_luminance", 0.5))
        prey_ang = float(sensory.get("visual_prey_angle", 0.0))
        threat = float(sensory.get("predator_threat", 0.0))
        flow = float(sensory.get("water_flow_velocity", 0.05))
        sound_hz = float(sensory.get("acoustic_stimulus_hz", 0.0))
        sound_db = float(sensory.get("acoustic_stimulus_db", 0.0))

        # 1. Drive sensory regions
        # Optic Tectum activation
        tectum_idxs = self.division_indices["Mesencephalon"]
        sensory_drive = np.zeros(self.num_regions, dtype=np.float32)
        
        # Lateral visual asymmetry: positive angle activates left tectum (contralateral)
        angle_rad = np.clip(prey_ang / 90.0, -1.0, 1.0)
        for idx in tectum_idxs:
            name = self.region_names[idx]
            base_vis = vis_lum * 0.4
            if "_L" in name:
                sensory_drive[idx] += base_vis + max(0.0, angle_rad) * 0.6
            elif "_R" in name:
                sensory_drive[idx] += base_vis + max(0.0, -angle_rad) * 0.6

        # Lateral line & Cerebellum flow activation
        cereb_idxs = self.division_indices["Cerebellum"]
        for idx in cereb_idxs:
            sensory_drive[idx] += min(1.0, abs(flow) * 2.5) * 0.5

        # Auditory / Lateral line drive to Hindbrain & Torus semicircularis
        if sound_db > 40.0:
            sound_intensity = min(1.0, (sound_db - 40.0) / 60.0)
            for idx in self.division_indices["Rhombencephalon"]:
                if "Auditory" in self.region_names[idx] or "LateralLine" in self.region_names[idx]:
                    sensory_drive[idx] += sound_intensity * 0.8

        # 2. Inter-regional Connectome Recurrent Dynamics
        # dC/dt = -C/tau + W * C + Sensory + Noise
        decay_factor = float(np.exp(-dt / 0.12)) # 120ms calcium decay
        synaptic_input = np.dot(self.tract_matrix.T, self.region_calcium) * 0.25
        noise = np.random.normal(0, 0.02, self.num_regions).astype(np.float32)

        self.region_calcium = self.region_calcium * decay_factor + synaptic_input * dt + sensory_drive * 0.4 + noise
        self.region_calcium = np.clip(self.region_calcium, 0.0, 1.5)

        # 3. Mauthner Escape Reflex Circuit (ultra-fast C-start)
        mauthner_triggered = False
        if threat > 0.65 and self.escape_cooldown <= 0.0:
            mauthner_triggered = True
            self.escape_cooldown = 0.5 # 500ms refractory
            # Surge rhombencephalic & spinal motor activity
            for idx in self.division_indices["Rhombencephalon"]:
                if "Mauthner" in self.region_names[idx]:
                    self.region_calcium[idx] = 1.4
        else:
            self.escape_cooldown = max(0.0, self.escape_cooldown - dt)

        # 4. Sonic Drumming Apparatus (Danionella 140 dB pulse generation)
        # Driven by social acoustic stimulation or forebrain arousal state
        sonic_drive = 0.0
        for idx in self.division_indices["Motor & Sonic Drumming"]:
            if "Sonic_Drumming" in self.region_names[idx]:
                sonic_drive += float(self.region_calcium[idx])

        # Also telencephalon emotional/social drive
        tel_drive = np.mean([self.region_calcium[i] for i in self.division_indices["Telencephalon"]])
        drumming_active = False
        drum_freq = 0.0
        drum_spl = 0.0

        if self.drum_refractory <= 0.0:
            if sonic_drive > 0.85 or (sound_hz > 50.0 and tel_drive > 0.4):
                drumming_active = True
                drum_freq = float(np.random.uniform(60.0, 120.0)) # 60-120 Hz pulse train
                drum_spl = float(np.random.uniform(132.0, 140.2)) # Up to 140.2 dB SPL!
                self.drum_refractory = float(np.random.uniform(0.3, 0.8)) # Refractory pause
        else:
            self.drum_refractory = max(0.0, self.drum_refractory - dt)

        # 5. Compute Motor Outputs
        # Spinal ventral root swimming rhythm + cerebellum balance
        spin_idxs = [i for i in self.division_indices["Motor & Sonic Drumming"] if "Sp_" in self.region_names[i]]
        left_motor = np.mean([self.region_calcium[i] for i in spin_idxs if "_L" in self.region_names[i]])
        right_motor = np.mean([self.region_calcium[i] for i in spin_idxs if "_R" in self.region_names[i]])

        if mauthner_triggered:
            # Escape burst: instant maximal thrust and unilateral sharp turn
            tail_thrust = 1.0
            heading_yaw = 1.0 if np.random.rand() > 0.5 else -1.0
            fin_pitch = 0.2
        else:
            # Normal swimming: rhythmic undulation modulated by motor excitation
            base_drive = float(np.clip((left_motor + right_motor) * 0.7, 0.05, 0.95))
            rhythm = float(0.5 + 0.5 * np.sin(self.step_count * 0.4))
            tail_thrust = float(np.clip(base_drive * rhythm, 0.0, 1.0))
            
            # Differential motor activation steers the fish
            steering_delta = float(right_motor - left_motor)
            heading_yaw = float(np.clip(steering_delta * 1.5, -1.0, 1.0))
            
            # Cerebellum balance provides vertical trim
            cereb_level = float(np.mean([self.region_calcium[i] for i in cereb_idxs]))
            fin_pitch = float(np.clip((cereb_level - 0.2) * 0.5, -1.0, 1.0))

        # 6. Global Population Statistics
        # Scale regional calcium to full 650,000 population firing rate (12 Hz to 45 Hz physiological range)
        mean_calcium = float(np.mean(self.region_calcium))
        pop_rate = float(12.5 + mean_calcium * 24.0) # Hz

        regional_summary = {}
        for div_name, idx_list in self.division_indices.items():
            regional_summary[div_name] = float(np.mean([self.region_calcium[i] for i in idx_list]))

        return DanioAction(
            tail_thrust=tail_thrust,
            heading_yaw=heading_yaw,
            fin_pitch=fin_pitch,
            drumming_sound_active=drumming_active,
            drumming_frequency_hz=drum_freq,
            drumming_spl_db=drum_spl,
            mauthner_escape=mauthner_triggered,
            population_firing_rate=pop_rate,
            regional_activity=regional_summary
        )

    def get_cranial_snapshot(self, sample_size: int = 2000) -> Dict[str, Any]:
        """
        Sample active 3D neuron coordinates and their calcium intensities for web visualization.
        """
        step = max(1, self.num_neurons // sample_size)
        sample_indices = np.arange(0, self.num_neurons, step)[:sample_size]
        
        sample_coords = self.coords_xyz[sample_indices]
        sample_regs = self.region_ids[sample_indices]
        sample_calcium = self.region_calcium[sample_regs]
        
        return {
            "coords": sample_coords.tolist(),
            "calcium": sample_calcium.tolist(),
            "regions": sample_regs.tolist()
        }

    def info(self) -> str:
        """Pretty summary of brain model."""
        meta = self.metadata
        return (
            f"========================================================\n"
            f" DANIO: Adult Danionella cerebrum Vertebrate Brain\n"
            f"========================================================\n"
            f" Organism:       {meta.get('organism')}\n"
            f" Neurons:        {self.num_neurons:,} vertebrate neurons\n"
            f" Brain Regions:  {self.num_regions} distinct anatomical structures\n"
            f" Cranial Volume: {meta.get('cranial_volume_mm3')} mm3 (Optical Transparency)\n"
            f" Acoustic Motor: {meta.get('sound_drumming_peak_db')} dB drumming pulse mechanism\n"
            f" Author:         {meta.get('author')}\n"
            f" Co-Author:      {meta.get('co_author')}\n"
            f" License:        {meta.get('license')}\n"
            f"========================================================"
        )
